CREATE TABLE IF NOT EXISTS "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL);
CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE IF NOT EXISTS "auth_group_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "auth_user_groups" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "auth_user_user_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" ON "auth_group_permissions" ("group_id", "permission_id");
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id");
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id");
CREATE UNIQUE INDEX "auth_user_groups_user_id_group_id_94350c0c_uniq" ON "auth_user_groups" ("user_id", "group_id");
CREATE INDEX "auth_user_groups_user_id_6a12ed8b" ON "auth_user_groups" ("user_id");
CREATE INDEX "auth_user_groups_group_id_97559544" ON "auth_user_groups" ("group_id");
CREATE UNIQUE INDEX "auth_user_user_permissions_user_id_permission_id_14a6b632_uniq" ON "auth_user_user_permissions" ("user_id", "permission_id");
CREATE INDEX "auth_user_user_permissions_user_id_a95ead1b" ON "auth_user_user_permissions" ("user_id");
CREATE INDEX "auth_user_user_permissions_permission_id_1fbb5f2c" ON "auth_user_user_permissions" ("permission_id");
CREATE TABLE IF NOT EXISTS "django_admin_log" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "action_flag" smallint unsigned NOT NULL CHECK ("action_flag" >= 0), "change_message" text NOT NULL, "content_type_id" integer NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "action_time" datetime NOT NULL);
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id");
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" ("user_id");
CREATE TABLE IF NOT EXISTS "django_content_type" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL);
CREATE UNIQUE INDEX "django_content_type_app_label_model_76bd3d3b_uniq" ON "django_content_type" ("app_label", "model");
CREATE TABLE IF NOT EXISTS "auth_permission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "content_type_id" integer NOT NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "codename" varchar(100) NOT NULL, "name" varchar(255) NOT NULL);
CREATE UNIQUE INDEX "auth_permission_content_type_id_codename_01ab375a_uniq" ON "auth_permission" ("content_type_id", "codename");
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id");
CREATE TABLE IF NOT EXISTS "auth_group" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(150) NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS "auth_user" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "password" varchar(128) NOT NULL, "last_login" datetime NULL, "is_superuser" bool NOT NULL, "username" varchar(150) NOT NULL UNIQUE, "last_name" varchar(150) NOT NULL, "email" varchar(254) NOT NULL, "is_staff" bool NOT NULL, "is_active" bool NOT NULL, "date_joined" datetime NOT NULL, "first_name" varchar(150) NOT NULL);
CREATE TABLE IF NOT EXISTS "cms_emailconfirmation" ("created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "code" varchar(100) NOT NULL, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "cms_emailconfirmation_user_id_c3b7d863" ON "cms_emailconfirmation" ("user_id");
CREATE TABLE IF NOT EXISTS "cms_profile" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "is_verified" bool NOT NULL, "user_id" integer NOT NULL UNIQUE REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" datetime NOT NULL);
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");
CREATE TABLE IF NOT EXISTS "cms_tag" ("created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(255) NOT NULL);
CREATE TABLE IF NOT EXISTS "cms_type" ("created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(255) NOT NULL, "description" text NULL);
CREATE TABLE IF NOT EXISTS "cms_activity" ("created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "activity_id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "activity_name" varchar(255) NOT NULL, "data" text NULL CHECK ((JSON_VALID("data") OR "data" IS NULL)), "description" text NULL);
CREATE TABLE IF NOT EXISTS "cms_place_types" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "place_id" integer NOT NULL REFERENCES "cms_place" ("place_id") DEFERRABLE INITIALLY DEFERRED, "type_id" integer NOT NULL REFERENCES "cms_type" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "cms_place_accommodation_places_nearby" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "from_place_id" integer NOT NULL REFERENCES "cms_place" ("place_id") DEFERRABLE INITIALLY DEFERRED, "to_place_id" integer NOT NULL REFERENCES "cms_place" ("place_id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "cms_place_tags" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "place_id" integer NOT NULL REFERENCES "cms_place" ("place_id") DEFERRABLE INITIALLY DEFERRED, "tag_id" integer NOT NULL REFERENCES "cms_tag" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "cms_place_types_place_id_type_id_2066ba67_uniq" ON "cms_place_types" ("place_id", "type_id");
CREATE INDEX "cms_place_types_place_id_3c6fccd7" ON "cms_place_types" ("place_id");
CREATE INDEX "cms_place_types_type_id_1911f193" ON "cms_place_types" ("type_id");
CREATE UNIQUE INDEX "cms_place_accommodation_places_nearby_from_place_id_to_place_id_41992ae6_uniq" ON "cms_place_accommodation_places_nearby" ("from_place_id", "to_place_id");
CREATE INDEX "cms_place_accommodation_places_nearby_from_place_id_3a86e951" ON "cms_place_accommodation_places_nearby" ("from_place_id");
CREATE INDEX "cms_place_accommodation_places_nearby_to_place_id_fd70f474" ON "cms_place_accommodation_places_nearby" ("to_place_id");
CREATE UNIQUE INDEX "cms_place_tags_place_id_tag_id_95e0ecd2_uniq" ON "cms_place_tags" ("place_id", "tag_id");
CREATE INDEX "cms_place_tags_place_id_7ea6b93d" ON "cms_place_tags" ("place_id");
CREATE INDEX "cms_place_tags_tag_id_8a0fdadc" ON "cms_place_tags" ("tag_id");
CREATE TABLE IF NOT EXISTS "cms_district" ("created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(255) NOT NULL);
CREATE TABLE IF NOT EXISTS "cms_province" ("created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(255) NOT NULL);
CREATE TABLE IF NOT EXISTS "cms_placeactivity" ("created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "description" text NULL, "data" text NULL CHECK ((JSON_VALID("data") OR "data" IS NULL)), "activity_id" integer NULL REFERENCES "cms_activity" ("activity_id") DEFERRABLE INITIALLY DEFERRED, "place_id" integer NULL REFERENCES "cms_place" ("place_id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "cms_placeactivity_activity_id_89878402" ON "cms_placeactivity" ("activity_id");
CREATE INDEX "cms_placeactivity_place_id_9c2ece36" ON "cms_placeactivity" ("place_id");
CREATE TABLE IF NOT EXISTS "cms_place" ("created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "place_id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "place_name" varchar(255) NOT NULL, "description" text NULL, "district_id" integer NULL REFERENCES "cms_district" ("id") DEFERRABLE INITIALLY DEFERRED, "ticket_price" decimal NULL, "location" varchar(255) NULL, "latitude" real NULL, "longitude" real NULL, "how_to_visit" text NULL, "best_time_to_visit_in_year" varchar(100) NULL, "data" text NULL CHECK ((JSON_VALID("data") OR "data" IS NULL)), "province_id" integer NULL REFERENCES "cms_province" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "cms_place_district_id_c999faa1" ON "cms_place" ("district_id");
CREATE INDEX "cms_place_province_id_8f3933ca" ON "cms_place" ("province_id");
CREATE TABLE IF NOT EXISTS "csvimport_csvimport" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "field_list" text NOT NULL, "upload_file" varchar(100) NOT NULL, "file_name" varchar(255) NOT NULL, "encoding" varchar(32) NOT NULL, "upload_method" varchar(50) NOT NULL, "error_log" text NOT NULL, "import_date" date NOT NULL, "import_user" varchar(255) NOT NULL, "model_name" varchar(255) NOT NULL);
CREATE TABLE IF NOT EXISTS "csvimport_importmodel" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "numeric_id" integer unsigned NOT NULL CHECK ("numeric_id" >= 0), "natural_key" varchar(100) NOT NULL, "csvimport_id" bigint NOT NULL REFERENCES "csvimport_csvimport" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "csvimport_importmodel_csvimport_id_5a422b1c" ON "csvimport_importmodel" ("csvimport_id");
