# Generated by Django 4.2.13 on 2024-07-04 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('data', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('place_id', models.AutoField(primary_key=True, serialize=False)),
                ('place_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('district', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('how_to_visit', models.TextField()),
                ('accommodation_places_nearby', models.TextField()),
                ('best_time_to_visit_in_year', models.CharField(max_length=100)),
                ('tags', models.CharField(max_length=255)),
                ('data', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlaceActivity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('data', models.JSONField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_activity', to='cms.activity')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_activity', to='cms.place')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='place',
            name='activities',
            field=models.ManyToManyField(related_name='places', through='cms.PlaceActivity', to='cms.activity'),
        ),
    ]
