# Generated by Django 4.2.13 on 2024-07-04 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_activity_place_placeactivity_place_activities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='activity',
            name='data',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.RemoveField(
            model_name='place',
            name='accommodation_places_nearby',
        ),
        migrations.AlterField(
            model_name='place',
            name='best_time_to_visit_in_year',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='data',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='district',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='how_to_visit',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='province',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='place',
            name='tags',
        ),
        migrations.AlterField(
            model_name='place',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='placeactivity',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_activities', to='cms.activity'),
        ),
        migrations.AlterField(
            model_name='placeactivity',
            name='data',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='placeactivity',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='placeactivity',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_activities', to='cms.place'),
        ),
        migrations.AddField(
            model_name='place',
            name='types',
            field=models.ManyToManyField(related_name='places', to='cms.type'),
        ),
        migrations.AddField(
            model_name='place',
            name='accommodation_places_nearby',
            field=models.ManyToManyField(related_name='places_nearby', to='cms.place'),
        ),
        migrations.AddField(
            model_name='place',
            name='tags',
            field=models.ManyToManyField(related_name='places', to='cms.tag'),
        ),
    ]
