# Generated by Django 4.2.13 on 2024-07-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_district_province_alter_activity_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='accommodation_places_nearby',
            field=models.ManyToManyField(blank=True, related_name='places_nearby', to='cms.place'),
        ),
    ]
