# Generated by Django 4.2.13 on 2024-09-03 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_image_place_ratings_place_header_image_place_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='ratings',
            new_name='rating',
        ),
    ]
