# Generated by Django 4.2.13 on 2024-08-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0008_image_place_ratings_place_header_image_place_images"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="image",
        ),
        migrations.AddField(
            model_name="image",
            name="image_url",
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
