# Generated by Django 4.2.13 on 2024-09-03 14:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0008_plan"),
        ("cms", "0009_rename_ratings_place_rating"),
    ]

    operations = []
