# Generated by Django 4.2.13 on 2024-08-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0009_remove_image_image_image_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image_url",
            field=models.CharField(max_length=1001),
        ),
    ]
