# Generated by Django 4.2.13 on 2024-08-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0011_alter_image_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="data",
            field=models.TextField(blank=True, null=True),
        ),
    ]
