# Generated by Django 4.2.13 on 2024-09-04 10:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0012_rename_activity_id_activity_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="place",
            old_name="place_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="place",
            old_name="place_name",
            new_name="name",
        ),
    ]
