# Generated by Django 4.2.13 on 2024-08-30 17:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0012_image_data"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image",
            old_name="image_url",
            new_name="url",
        ),
    ]
