# Generated by Django 4.2.13 on 2024-09-05 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_rename_activity_id_activity_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferred_activities',
            field=models.ManyToManyField(blank=True, related_name='user_preferred_activities', to='cms.activity'),
        ),
    ]
