# Generated by Django 4.2.13 on 2024-09-05 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_profile_preferred_activities'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cms.district'),
        ),
    ]
