# Generated by Django 4.2.13 on 2024-09-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_profile_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='imageUrl',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
