# Generated by Django 4.2.13 on 2024-08-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0002_rename_guide_id_message_guide_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="isAI",
            field=models.BooleanField(default=True),
        ),
    ]
