# Generated by Django 4.2.13 on 2024-09-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0004_rename_conversation_id_conversation_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="time",
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
